# 进程号
pid = "./run/node.pid"
# 统一时区设置。项目中的时间获取请使用xtime.Now()
timezone = "Local"

[cluster]
    [cluster.node]
    id = ""
    name = "hall"
    timeout = "1s"
    codec = "proto"

[locate]
    [locate.redis]
        addrs = [
            "127.0.0.1:6379",
        ] # 客户端连接地址
        db = 0 # 数据库号
        username = "" # 用户名
        password = "" # 密码
        maxRetries = 3 # 最大重试次数
        prefix = "due" # key前缀

[registry]
    [registry.consul]
    # 客户端连接地址，默认为127.0.0.1:8500
    addr = "127.0.0.1:8500"
    # 是否启用健康检查，默认为true
    healthCheck = true
    # 健康检查时间间隔（秒），仅在启用健康检查后生效，默认为10
    healthCheckInterval = 10
    # 健康检查超时时间（秒），仅在启用健康检查后生效，默认为5
    healthCheckTimeout = 5
    # 是否启用心跳检查，默认为true
    heartbeatCheck = true
    # 心跳检查时间间隔（秒），仅在启用心跳检查后生效，默认为10
    heartbeatCheckInterval = 10
    # 健康检测失败后自动注销服务时间（秒），默认为30
    deregisterCriticalServiceAfter = 30

[packet]
    byteOrder       = "big" # 字节序，little | big
    seqBytes        = 2     # 序列号字节长度（字节）
    serverTypeBytes = 2     # 服务器类型字节长度（字节）
    routeBytes      = 2     # 路由字节长度（字节）

[log]
    file              = "./log/due.log"              # 日志输出文件
    level             = "debug"                      # 日志输出级别，可选：debug | info | warn | error | fatal | panic
    format            = "text"                       # 日志输出格式，可选：text | json
    stdout            = true                         # 是否输出到终端
    timeFormat        = "2006/01/02 15:04:05.000000" # 时间格式，标准库时间格式
    stackLevel        = "error"                      # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
    fileMaxAge        = "2d"                         # 文件最大留存时间，d:天、h:时、m:分、s:秒
    fileMaxSize       = 100                          # 文件最大尺寸限制，单位（MB）
    fileCutRule       = "day"                        # 文件切割方式
    callerFullPath    = true                         # 是否启用调用文件全路径
    classifiedStorage = true                         # 是否启用分级存储
    # zap日志组件。以下配置项如果不存在，则会使用log域中的默认配置项；如果均未配置，则会使用系统默认配置

# 配置中心
[config]
    # consul配置中心
    [config.consul]
        # 客户端连接地址
        addr = "127.0.0.1:8500"
        # 路径。默认为config
        path = "config"
        # 读写模式。可选：read-only | write-only | read-write，默认为read-only
        mode = "read-only"